#!/usr/bin/perl
 
use strict;
use warnings;
 
use CGI  qw(:standard);
use CGI::Carp qw(fatalsToBrowser);
use JSON;

$| = 1;

print header('application/json');
my $json = new JSON;
$json = $json->pretty() ;
$json = $json->ascii() ;
my $jsonStructure;
my $username = url_param('username');
if ( $username eq "james_" ) {
	$jsonStructure->{result}="User name in use";
} else  {
	$jsonStructure->{result}="User name available";
}
print  $json->encode($jsonStructure);
