#!/usr/bin/perl
 

use strict;
use warnings;
use lib '/var/www/vault/cgi' ;


 
use CGI  qw(:standard);
use CGI::Carp qw(fatalsToBrowser);
use Error qw(:try);
use Vault::core;

$| = 1;

my $vault = Vault::core->new();
my $validation_string= param('validation_string');
if ($validation_string eq 'VALID' ) {
	print 'Location: '.$vault->get_default_value('cgi_path')."/index.cgi?registered_state=notregisted\n\n" ;
	exit 0 ;
}

my $found_user=$vault->{schema}->resultset('User')->search ( {
		'validation_string' => $validation_string
		} )->single;
if ( defined($found_user) and $found_user != 0 ) {
	# Found the right user.
	$found_user->update( { 'validation_string' => 'VALID' } );
	print 'Location: '.$vault->get_default_value('cgi_path')."/index.cgi?registered_state=registed\n\n" ;
	exit 0;
}
print 'Location: '.$vault->get_default_value('cgi_path')."/index.cgi?registered_state=notregisted\n\n" ;
exit 0 ;
