#!/usr/bin/perl
 
use strict;
use warnings;
 
use CGI;
use CGI::Carp qw(fatalsToBrowser);
use CGI::Session qw/-ip-match/;
use Vault::core;
use Template;
$| = 1;
 
#--------------------------------------------------
# configuration
#--------------------------------------------------
 
my $cgi = CGI->new(  );
my $vault = Vault::core->new();
my $cookie=$cgi->cookie("VAULTID") || undef;
my $session = new CGI::Session("driver:MySQL", $cookie, {Handle=>$vault->dbi()});
$vault->log_event('User: '.$session->param("username").' Session id ' .$cookie .' logged out',$Vault::core::LOG_INFO) ;
$session->delete();
print 'Location: '.$vault->get_default_value('cgi_path')."/index.cgi\n\n" ;
exit 0;
